### ISSUE TITLE
Any Plans to Port The Code To ESP32?

### ISSUE THREAD

**Issue by ianwillianb** [creotiv/MiBand2#13]
Since there are people who were able to read heart rate from the Polar H7 using ESP32, do you have plans to port the code to get data from the miband 2 using the ESP32?

**Comment by creotiv** [comment]
Sorry but no, this code was developed for my data science project on
prediction of people activity type by gyro and heart rate, so i need only
laptop.

**Comment by SiOnOu** [comment]
> Since there are people who were able to read heart rate from the Polar H7 using ESP32, do you have plans to port the code to get data from the miband 2 using the ESP32?

I have written a demo to get heart rate data from miband2 using ESP32. You can find it here: https://github.com/SiOnOu/esp32_miband2 (supports esp32 library 1.0.0, some unused codes may need to be removed). And now I wonder how to re-connect the band when ESP32  cannot connect to its services or it is lost (since the distance is too far or consuming of the battery)
